# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CustomCollectionView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomCollectionView
    pod 'AFDateHelper'
    pod 'CrittercismSDK'

  target 'CustomCollectionViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
